//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WSSlider
    {
        public int SL { get; set; }
        public string Location { get; set; }
        public bool Chosen { get; set; }
        public int Ordering { get; set; }
    }
}
